require("dotenv").config();
const bcrypt = require("bcrypt");
const express = require('express');
const cors = require("cors");
const {connectDB} = require("./db");
const {getDB} = require("./db");

const app = express();
const port = process.env.PORT || 3000;




app.use(express.json());
app.use(cors());

connectDB(); //database connection

///////////////////////LOGIN/////////////////////////
app.post("/login", async (req, res) => { //receive login data from front-end
    const {user, password} = req.body; //destructures username and password
  if (!user || !password) {
    return res.status(400).send({message: "Please fill in both fields"}) //checks if every field is filled in
  } 
    try {
      const db = getDB(); //user the existing DB connection
      const usersCollection = db.collection("users"); //selects the users collection
      const userExists = await usersCollection.findOne({user}); //checks if a doesn't exist

      if (!userExists) {
        return res.status(409).send({message: "invalid input"}); //this message plays if this user exists for them to login
    };

    const correctPassword = await bcrypt.compare( // compares the passwords: 
      password,
      userExists.password
    );

    if (!correctPassword) {
      return res.status(401).send({message: "Credentials don't match"}); //checks if password is correct
    };
    //logs you in and returns with what user you logged in with
    res.send({message: "Succesfully logged in!",
      user: userExists.user
    });
    
  }catch(error) {
      console.error(error);
      res.status(500).send({message: "Failure to login"})
    }
});
///////////////////////LOGIN/////////////////////////

///////////////////////REGISTER/////////////////////////
app.post("/register", async (req, res) =>{
  //console.log("BODY:", req.body);
  const {user, password} = req.body; //destructures everything

  if (!user || !password) { //checks if both fields aren't empty
    return res.status(400)
    .send({message: "Please fill in the required fields"});
  } try {
    const db = getDB(); //uses the existing DB connection
    const usersCollection = db.collection("users"); //selects the users collection
    const userExists = await usersCollection.findOne({user}); //checks if a user has the same name

    if (userExists) {
      return res.status(409).send({message: "This user already exists"}); //this message plays if theres a user with the inputted name
    };
    const hashedpassword = await bcrypt.hash(password, 10);


    //safely stores user
    await usersCollection.insertOne({
      user: user,
      password: hashedpassword
    });
      res.send({message: "Registering user succesful!"});

  } catch(error) {
    console.error(error);
      res.status(500).send({message: "Error password hashing"});
  }
});
///////////////////////REGISTER/////////////////////////

///////////////////////GET COACHES/////////////////////////

app.get("/coaches", async (req, res) => {
  try {
      const db = getDB(); //uses the existing DB connection
      const coachesCollection = db.collection("coaches"); //selects the coaches collection

      const coaches = await coachesCollection.find().toArray();

      res.send(coaches);
  } catch(error) {
    console.error(error);
    res.status(500).send({message: "Failure to find any coaches"})
  }
});
///////////////////////GET COACHES/////////////////////////

///////////////////////CREATE COACH (if logged in)/////////////////////////
app.post("/coaches", async (req, res) => {
  try {
  const {name, game, price, intro, facts} = req.body; //destructures everything

  //validates information
  if (!name || !game || !price || !intro) {
    return res.status(400).send({
      message: "Missing required info."
    });
  }
  const db = getDB();
  const coachesCollection = db.collection("coaches");
  const createdCoach = { //creates a new coach in an object
    name,
    game,
    price,
    intro,
    facts: facts || []
  };
  
  await coachesCollection.insertOne(createdCoach); //adds the coach to the mongo collection
  res.status(201).send({
    message: "Welcome aboard, coach",
    createdCoach
  });
  } catch(error) {
    console.error(error);
    res.status(500).send({
      message: "Coach could not be created"
    });
  }

});
///////////////////////CREATE COACH/////////////////////////
///////////////////////DELETE COACH/////////////////////////
const {ObjectId} = require("mongodb"); //This line of code was generated by Chatgpt (check readme for chat session)
app.delete("/coaches/:id", async (req, res) => {
  try {
  const coachId = req.params.id; //This line of code was generated by Chatgpt (check readme for chat session)
  
  const db = getDB(); //uses the existing DB connection
  const coachesCollection = db.collection("coaches");//selects the coaches collection

  const result = await coachesCollection.deleteOne({ //This line of code was generated by Chatgpt (check readme for chat session)
    _id: new ObjectId(coachId)
  });
  //This code was generated by Chatgpt (check readme for chat session)
  if (result.deleteCount === 0) {
    return res.status(404).send({
      message: "Coach not found"
    });
  } 
    ///////////////////////////////////////////////////////////////////
  } catch(error) {
    console.error(error);
    res.status(500).send({
      message: "Coach could not be deleted"
    });
  }
  
});

///////////////////////DELETE COACH/////////////////////////



//starts up the server
app.listen(port, () => {
  console.log(`Example app listening on port ${port}`)
});